/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author Aluno
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Sair");

        jLabel1.setText("jLabel1");

        jMenu1.setText("File");

        jMenuItem1.setText("Novo Cliente");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Atualizar Cliente");
        jMenu1.add(jMenuItem2);

        jSair.setText("Sair");
        jMenu1.add(jSair);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1)))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addComponent(jButton1)
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) { 
    //GEN-FIRST:event_jMenuItem1ActionPerformed 
    // TODO add your handling code here: 
         CadCliente CadCli = new CadCliente(); 
         CadCli.setVisible(true); 
    }//GEN-LAST:event_jMenuItem1ActionPerformed 
    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) { 
    //GEN-FIRST:event_jMenu1ActionPerformed 
    // TODO add your handling code here: 
    //CadCliente CadCli = new CadCliente(); 
    //CadCli.setVisible(true); 
    }//GEN-LAST:event_jMenu1ActionPerformed 
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) { 
    //GEN-FIRST:event_jMenuItem2ActionPerformed 
    // TODO add your handling code here: 
        AtuCliente atucliente = new AtuCliente(); 
        atucliente.setVisible(true); 
    }//GEN-LAST:event_jMenuItem2ActionPerformed 
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) { 
    //GEN-FIRST:event_jButton1ActionPerformed 
    dispose(); // TODO add your handling code here: 
    }//GEN-LAST:event_jButton1ActionPerformed 
    private void jSairActionPerformed(java.awt.event.ActionEvent evt) { 
    //GEN-FIRST:event_jSairActionPerformed 
    // TODO add your handling code here: 
    dispose(); 
    }//GEN-LAST:event_jSairActionPerformed 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try { 
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager. 
            getInstalledLookAndFeels()) { 
            if ("Nimbus".equals(info.getName())) { 
            javax.swing.UIManager.setLookAndFeel(info.getClassName()); 
            break; 
            } 
            } 
            } catch (ClassNotFoundException ex) { 
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level .SEVERE, null, ex); 
            } catch (InstantiationException ex) { 
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level .SEVERE, null, ex); 
            } catch (IllegalAccessException ex) { 
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level .SEVERE, null, ex); 
            } catch (javax.swing.UnsupportedLookAndFeelException ex) { 
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level .SEVERE, null, ex); 
            } 
//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jSair;
    // End of variables declaration//GEN-END:variables
}
